name: CI / CD Pipeline for ChatBot AGI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment for Flask
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Set up Node.js for React
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install and build frontend
      working-directory: agi-chatbot
      run: |
        npm install
        npm run build

    # Copy built frontend files to the Backend/static folder
    - name: Move frontend build to backend static folder
      run: |
        mkdir -p Backend/static
        cp -r agi-chatbot/build/* Backend/static/

    # Build the Docker image
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/agi_chatbot:latest .

    # Deploy the application (replace this with your deployment steps)
    # - name: Deploy application
    #   run: |
    #     echo "Deploying application (replace with your deployment logic)"
